name: Java CI with Maven
on:
  push:
    branches:
  pull_request:
    branches:
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do
          if mysqladmin ping -h127.0.0.1 -uroot -proot &> /dev/null; then
           echo "MySQL is up and running"
           break
          fi
          echo "Waiting for MySQL..."
          sleep 2
          done
      - name: Run database migrations
        run: |
          mysql -h127.0.0.1 -uroot -proot test_database < create_table.sql
      - name: Verify MySQL Service
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "SHOW DATABASES;"
      - name: Build with Maven
        run: mvn -B package --file pom.xml -X
      - name: Test with Maven
        run: mvn test -P local
